### ISSUE TITLE
Possible freeze in Safari 7.0.2 under Mac OS X 10.9.2 beta 13C339

### ISSUE THREAD

**Issue by lukaskubanek** [jurre/switchr#4]
Is it possible that the `switchr` plugin freezes Safari under the new beta of Mavericks?

Since the update I always had a hanging Safari process which consumed 80-90% of my CPU. I did a little research and found that it may be caused by an extension. I tried to disable all of them and it worked fine. Afterwards I disabled `switchr` and all works fine now.

Have you a possibility to test this issue? If not, how can I help you?

**Comment by jurre** [comment]
Hey @lukaskubanek, thanks for reporting this! I don't have a machine on the new beta yet, but I can try to install it on a VM and see what happens!

**Comment by lukaskubanek** [comment]
Maybe it's just a false alarm. I activated `switchr` again and so far all works well. I close this issue for now and if I find an issue again, I let you know.

Thanks for this cute utility!

**Comment by jurre** [comment]
:+1:
